### ISSUE TITLE
Internet Explorer doesn't interpret loader correctly

### ISSUE THREAD

**Issue by Daddelbob** [ngneat/content-loader#12]
The content-loader displays just fine in Chrome, but has a way different and unexpected behaviour in IE 11.
The Loader shrinks to a 3x3 cm area where there should be a loader covering the whole page, 20x20cm and bigger.
Internet Explorer Version: 11.0.9600.19080

**Comment by NetanelBasal** [comment]
Can you check the original [repo](https://github.com/danilowoz/react-content-loader) for this issue?

**Comment by Daddelbob** [comment]
Checked it, there is this closed Issue for propably the same problem 

Report: "There was no transition and it was not the right size."
Answer: "Unfortunately, Edges and IE don't have support to SVG Animate (https://developer.mozilla.org/en-US/docs/Web/SVG/Element/animate)"
https://github.com/danilowoz/react-content-loader/issues/92#issuecomment-380611941.

No solution so far.

You might additionally consider following issues aswell: https://github.com/danilowoz/react-content-loader/issues/93#issuecomment-387918027

**Comment by NetanelBasal** [comment]
Thanks, I will.
