### ISSUE TITLE
Please fix "Support Safari browser" in Angular 6

### ISSUE THREAD

**Issue by kvandake** [ngneat/content-loader#17]
## Related issue:
NetanelBasal/ngx-content-loader#8

<img width="1440" alt="screen shot 2018-07-28 at 11 28 03" src="https://user-images.githubusercontent.com/16502104/43354682-790ed02c-9259-11e8-8135-d65e1262af53.png">

<img width="1025" alt="screen shot 2018-07-28 at 11 28 46" src="https://user-images.githubusercontent.com/16502104/43354686-86f53a28-9259-11e8-9d43-7f35d8d6de5d.png">

**Comment by muhlucas** [comment]
I found the solution in a reject [PR](https://github.com/danilowoz/react-content-loader/pull/101). 

I've created a script to fix this while we wait for a new version.

```
let rects = document.getElementsByTagName("rect");
if(rects.length > 0)
	for (let i = 0; i < rects.length; i++) {
		if (rects[i].hasAttribute("clip-path") && rects[i].hasAttribute("style")) {
			rects[i].setAttribute("clip-path",
				rects[i].getAttribute("clip-path").replace("#", window.location.href + "#"));
			rects[i].setAttribute("style",
				rects[i].getAttribute("style").replace("#", window.location.href + "#"));
		}
	}
```

**Comment by ruxiang05** [comment]
Is this fix also for Angular 5?

**Comment by NetanelBasal** [comment]
Sure

**Comment by ruxiang05** [comment]
I'm having a hard time making this work. 

``
<content-loader speed="2" primaryColor="#f7c498" width="100" height=".5" secondaryColor="#fea467">
   <svg:rect width="100%" height=".5" y="0" x="0" rx="0" ry="0" />
</content-loader>
`` 
Am I doing something wrong?
