### ISSUE TITLE
Named router outlet 

### ISSUE THREAD

**Issue by framasev** [ngneat/content-loader#46]
## I'm submitting a...

<pre><code>
[*] Bug report  
</code></pre>

## Current behavior
Named router outlet pathnames (with double slash) reproduce same issue with black rendered svg

## Environment

<pre><code>
Angular version: 8.2.8

Browser:
- [*] Chrome (desktop) version 77

Others:

</code></pre>

**Comment by Steven-Harris** [comment]
I believe this is the same issue as #52

**Comment by NetanelBasal** [comment]
Check v6.0
