### ISSUE TITLE
content loader is not responsive

### ISSUE THREAD

**Issue by jstechaut** [ngneat/content-loader#49]
There are responsive issues in web and mobile. Is there any possibility to change width according to screen sizes

**Comment by NetanelBasal** [comment]
You're welcome to submit a PR

**Comment by Steven-Harris** [comment]
@jstechaut could you give an example?  I am not seeing any responsive issues in chrome DevTools.

**Comment by IsaacSomething** [comment]
> @jstechaut could you give an example? I am not seeing any responsive issues in chrome DevTools.

I dont think is it actually issue, it just does not change width or height based on screen size

**Comment by Steven-Harris** [comment]
That's what confuses me @IsaacSomething, they do resize based on the screensizes

**Comment by IsaacSomething** [comment]
Yeah you are right, I wonder if its maybe a specific implementation with a `svg:path`, maybe this issue should be closed or explained a bit more
