### ISSUE TITLE
Not possible to create donut shape

### ISSUE THREAD

**Issue by dolanmiu** [ngneat/content-loader#75]
When doing so, it simply creates a circle

Based my circle on:

https://stackoverflow.com/questions/8193675/draw-a-hollow-circle-in-svg

so:

```html
<content-loader [viewBox]="'0 0 800 800'">
  <svg:circle cx="100" cy="100" r="100" fill="#fff"></svg:circle>
  <svg:circle cx="100" cy="100" r="80" fill="transparent"></svg:circle>
</content-loader>
```

**Comment by dolanmiu** [comment]
Found the solution by using, with great results:

```html
    <svg:path d="M 0 50 A 1 1 0 1 1 100 50 a 1 1 0 1 1 -100 0 z m 20 0 A 1 1 0 0 0 80 50 A 1 1 0 0 0 20 50" fill="yellow" stroke="black"/>
```

![Screenshot 2021-01-31 at 21 20 44](https://user-images.githubusercontent.com/2917613/106398350-382f3300-640a-11eb-9dac-a53223248c19.png)

**Comment by NetanelBasal** [comment]
Looks good

**Comment by NetanelBasal** [comment]
I'm closing the issue. Thanks for the demo.
